### ISSUE TITLE
Reuse slim-auth in the same job

### ISSUE THREAD

**Issue by grzr** [og-gluon/slim-auth#16]
I would like to ask slim-auth for different project_id in the same jobs:

```yaml
- uses: og-gluon/slim-auth@v1
  with:
    project_id: my-project
    # ....
- run: make cd
- uses: og-gluon/slim-auth@v1
  with:
    project_id: another-project
    # ....
- run: make cd
```

currently there is an error that job is already registered
